//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        public Areas()
        {
            this.Renters = new HashSet<Renters>();
            this.Tenants = new HashSet<Tenants>();
        }
    
        public int id_area { get; set; }
        public string area { get; set; }
    
        public virtual ICollection<Renters> Renters { get; set; }
        public virtual ICollection<Tenants> Tenants { get; set; }
    }
}
