//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catgories
    {
        public Catgories()
        {
            this.Gowns = new HashSet<Gowns>();
        }
    
        public int id_catgory { get; set; }
        public string catgory { get; set; }
    
        public virtual ICollection<Gowns> Gowns { get; set; }
    }
}
