//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentingGownEntities : DbContext
    {
        public RentingGownEntities()
            : base("name=RentingGownEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Areas> Areas { get; set; }
        public DbSet<Catgories> Catgories { get; set; }
        public DbSet<Colors> Colors { get; set; }
        public DbSet<Gowns> Gowns { get; set; }
        public DbSet<Renters> Renters { get; set; }
        public DbSet<Seasons> Seasons { get; set; }
        public DbSet<Sets> Sets { get; set; }
        public DbSet<Tenants> Tenants { get; set; }
        public DbSet<Tenants_sets> Tenants_sets { get; set; }
    }
}
